# Root directory of your project
root = "."

# Exclude directories (like the vendor folder)
exclude_dir = ["tmp"]

# Watch `.go` files in the current directory
watcher = "."

# Command to run
cmd = "go run main.go"